admin-rails/config/routes.rb
Rails.application.routes.draw do

  mount SinatraApi.new => '/api'

  # ------ Users routes ------
    get   '/users/'               => 'users#index',   :as=>'users_home'
    get   '/users/all'            => 'users#all',     :as=>'users_all'
    get   '/users/signup'         => 'users#new',     :as=>'user_signup'
    post  '/users/signup'         => 'users#create'
    get   '/users/:id/profile'    => 'users#profile', :as=> 'user_profile'
    get   '/users/:id/edit'       => 'users#edit',    :as=> 'user_edit'
    put   '/users/:id/edit'       => 'users#update',  :as=> 'user_update'
    #delete '/user/delete/:id'     => 'user#destroy',  :as=> 'user_delete'
  # --------------------------

  # ------ Speakers routes ------
    resources :speakers
  # -----------------------------

  # ------ Talks routes --------
    resources :talks
    get   '/talks/speaker/:id'        => 'talks#new_by_speaker'
    get   '/talks/speaker_talks/:id'  => 'talks#my_talks'
    get   '/talks/api/json'           => 'talks#api'
    #post  '/users/signup'         => 'users#create'
  # ----------------------------

  # ------ Authentication routes ------
    get     '/login'              => 'session#new',       :as => 'login'
    post    '/login'              => 'session#create'
    delete  '/logout'             => 'session#destroy',   :as => 'logout'
  # --------------------------


  get 'pages/index'
  get 'pages/about'

   get   '/'                  => 'pages#index',      :as => 'root'
end

admin-rails/app/models/access_level.rb
class AccessLevel < ActiveRecord::Base
  has_one :user
end

admin-rails/app/models/speaker.rb
class Speaker < ActiveRecord::Base
  has_many :talks
  belongs_to :user

  # commented out due to issues integrating with backbone
  # mount_uploader :image, ImageUploader

end

admin-rails/app/models/talk.rb
class Talk < ActiveRecord::Base
  belongs_to :speaker

  def initialize(attributes={})
    super
    convert_time
  end

  def convert_time
    self.update(start_time: "#{self.date.hour}:#{self.date.min}")
  end

end

admin-rails/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  @ticket = "create_ticket"
 

  def create_ticket(email, talk)
    if Talk.find(talk).limit <= 0
     "ERROR"
    else  
      Ticket.create(:registra=>email, :talk_id=>talk)
    end

  end

end

admin-rails/app/models/user.rb
class User < ActiveRecord::Base

  has_one :speaker
  belongs_to :access_level
  #has_secure_password

  attr_accessor :password, :password_confirmation
  before_save :encrypt_password

  # Email validation
  validates :email, :presence => true, :uniqueness => true
  validates_format_of :email, :with => /@/

  # # Password validation
  validates :password, confirmation: true
  # validates_presence_of :password, :on => :create

  def self.authenticate(email, password)
    user = User.find_by(:email => email) || User.find_by(:username => email)
    if user && user.password_digest == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      login_path
    end
  end


  def encrypt_password

    if password.present?
      self.password_salt   = BCrypt::Engine.generate_salt
      self.password_digest = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

admin-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(:id => session[:user_id]) if session[:user_id]
  end

  def is_admin?
    current_user.access_level_id == 1
  end

  def is_speaker?

  end

  helper_method :current_user, :logged_in?, :is_admin?
end

admin-rails/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

admin-rails/app/controllers/session_controller.rb
class SessionController < ApplicationController

  # login form
  def new
    #@referral_url = request.env['HTTP_REFERER']
    if logged_in?
      redirect_to root_path
    end
  end

  def create

    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      render :json => { msg: [0, "You've successfully logged in."]}
      #render "You've successfully logged_in"
    else
      render :json => { msg: [1,"Your email and/or password were invalid. Please try again."]}
    end
    #binding.pry
    # @user = User.find_by(email: params[:email])

    # if @user && @user.authenticate(params[:password])
    #   session[:user_id] = @user.id
    #   # redirect_to root_path
    #   render :json => { msg: [0, "You've successfully logged in."]}
    # else
    #   render :json => { msg: [1,"Your email and/or password were invalid. Please try again."]}
    # end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

admin-rails/app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController

  def index
    @speakers = Speaker.all
  end

  def create
    @speaker = Speaker.new(speaker_params)

    if @speaker.save
      redirect_to "/speakers/#{@speaker.id}"
    else
      render :new
    end
  end

  def new
    @speaker = Speaker.new
  end

  def edit
    @speaker = Speaker.find(params[:id])
  end

  def show
    @speaker = Speaker.find(params[:id])
    @talks = Talk.where(speaker_id: params[:id])
  end

  def update
    @speaker = Speaker.find(params[:id])
    if @speaker.update(speaker_params)
      redirect_to speaker_path
    else
      render :edit
    end
  end

  def destroy
    @speaker = Speaker.find(params[:id])
    @speaker.destroy
    redirect_to speakers_path
  end

  def speaker_params
    binding.pry
    params.require(:speaker).permit(:name, :blurb, :image, :remote_image_url)
  end

end

admin-rails/app/controllers/talks_controller.rb
class TalksController < ApplicationController

  def index
    @talks = Talk.all
  end

  def api
    @talks = Talk.all
    @talks_json = @talks.to_json
    render :json => @talks_json
  end

  def create
    @talk = Talk.new(get_talk_params)
    if @talk.save
      redirect_to "/talks/#{@talk.id}"
    else
      render :new
    end
  end

  def new
    @talk = Talk.new
  end

  def new_by_speaker
    @talk = Talk.new
    @speaker = Speaker.find(params[:id])
  end

  def my_talks
    @talks = Talk.where(speaker_id: params[:id])
  end

  def show
    @talk = Talk.find(params[:id])
  end

  def edit
    @talk = Talk.find(params[:id])
  end

  def update
    @talk = Talk.find(params[:id])
    if @talk.update(get_talk_params)
      redirect_to talk_path
    else
      render :edit
    end
  end

  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy
    redirect_to '/talks'
  end

  def get_talk_params
    binding.pry
    params.require(:talk).permit(:title, :blurb, :description, :speaker_id, :date, :duration, :limit)
  end

end

admin-rails/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def all
    @users = User.all
    @access_type = AccessLevel.all
  end

  def new
    @user = User.new
    @access_level = AccessLevel.all
  end

  def create
    @user = User.new(get_user_params)
    binding.pry
    @user.save

    if @user.save
      # email user confirmation upon signup
      if Rails.configuration.x.mail_on_user_signup == true
        UserNotifier.send_signup_email(@user).deliver_now
      end
      redirect_to users_all_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    #@user = get_user_params
    #binding.pry
    if @user.update(get_user_params)
      redirect_to users_all_path
    else
      @errors = @user.errors.full_messages
      render :edit
    end
  end

  def profile
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_home
  end

  def get_user_params
    binding.pry
    params.require(:user).permit(:email, :access_level_id, :login_type, :password, :password_confirmation)

  end

end

admin-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

admin-rails/app/helpers/pages_helper.rb
module PagesHelper
end

admin-rails/app/helpers/talks_helper.rb
module TalksHelper
end

admin-rails/app/helpers/users_helper.rb
module UsersHelper
end

admin-rails/app/views/layouts/_login_form.html.haml
%ul.right
  - if logged_in?
    %li.logged_in
      logged in as #{current_user.email}
    %li
      = form_tag '/logout', method: :delete do
        %button.logout logout
  - else
    %li
      = link_to 'Login', login_path

admin-rails/app/views/layouts/_navbar.html.haml
%ul.left
  - if logged_in?
    - if is_admin?
      %li.has-dropdown.not-click

        %a{:href => users_all_path } Users
        %ul.dropdown

          %li
            = link_to 'User Index', users_home_path
          %li
            = link_to 'Sign Up', user_signup_path
          %li
            = link_to 'Show all users', users_all_path

    %li.has-dropdown.not-click
      %a{:href => speakers_path } Speakers
      %ul.dropdown
        - if is_admin?
          %li
            =link_to 'Add Speaker', new_speaker_path
          %li
            =link_to 'All Speakers', speakers_path
        - if !is_admin?
          %li
            =link_to 'My Profile', "/speakers/#{current_user.speaker.id}"

    %li.has-dropdown.not-click
      %a{:href => talks_path } Talks
      %ul.dropdown
        %li
          =link_to 'Add Talk', new_talk_path
        - if is_admin?
          %li
            =link_to 'All Talks', talks_path

        - if !is_admin?
          %li
            =link_to 'My Talk', "/talks/speaker_talks/#{current_user.speaker.id}"

admin-rails/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wdiconf
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Montserrat:400,700'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    /= javascript_include_tag 'jquery-ui' => true
    = csrf_meta_tags
  %body

    %nav.top-bar{"data-topbar" => "", :role => "navigation"}
      %section.navbar-wrapper
        %ul.title-area
          / Title Area
          %li.name
            %h1
              %a{:href => root_path} Admin Rails
          / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
          %li.toggle-topbar.menu-icon
            %a{:href => ""}
              %span Menu
        %section.top-bar-section
          = render '/layouts/navbar'
          = render '/layouts/login_form'

    %div.container
      = yield

admin-rails/app/views/pages/_side_navbar.html.haml
%div.side-nav
  %h2 Users
  %ul
    %li
      = link_to 'User Index', users_home_path
    %li
      = link_to 'Sign Up', user_signup_path
    %li
      = link_to 'Show all users', users_all_path
  %h2 Speakers
  %ul
    %li
      =link_to 'Sign Up', new_speaker_path
    %li
      =link_to 'All Speakers', speakers_path
  %h2 Talks
  %ul
    %li
      =link_to 'Add Talk', new_talk_path
    %li
      =link_to 'All Talks', talks_path

admin-rails/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<ul class="list_table">
  <li>
    <% @users.each do |user| %>
      <%= user.email %>
      <a href="1/profile">Show</a>
      <a href="1/edit">Edit</a>
    <% end %>
  </li>
</ul>


index.html.erb
<% talks = @talks.to_json %>
<%= talks[0] %>
<script>
  console.log("#{<%= talks[0] %>}");
  var talks = parseJSON(<%= @talks_json %>);
  debugger;
  // $.each(<%= @talks_json %>, function(x){
  //   console.log(<%= @blach %>);
  // });
</script>

admin-rails/app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.erb
.form
  = form_tag
  %p
    %label{:for => "talk_title"} Talk Title
    %input{:name => "talk_title", :type => "text"}/
  %p
    %label{:for => "talk_blurb"} Talk Blurb
    %input{:name => "talk_blurb", :type => "text"}/
  %p
    %label{:for => "talk_desc"} Talk Description
    %textarea{:name => "talk_desc"}
  %p
    %label{:for => "talk_desc"} date
    %input{:disabled => "disabled", :name => "talk_date", :type => "date", :value => "2015-05-29"}/
  %p
    %label{:for => "talk_desc"} time
    %input{:max => "16:30:00", :min => "10:00:00", :name => "talk_time", :type => "time"}/
  %p
    %label{:for => "talk_desc"} Speaker
    %select#speaker_name{:name => "speaker_name"}
      %option{:value => "100"} Daniel Tsui
  %input{:name => "limit", :type => "hidden", :value => "30"}/
  %input{:name => "duration", :type => "hidden", :value => "60"}/
  %input{:type => "submit"}/
  = end
:javascript
  $('#add_talk').on('click', function() {
    $('.talk_form').html(#{render 'form'});
  });

admin-rails/app/views/pages/index.html.haml
- if logged_in?
  = render 'side_navbar'
- else
  %section.login-wrapper
    %h1 Please login to proceed
    = render '/session/form'

admin-rails/app/views/session/_form.html.haml
= form_tag '/login' do
  = label_tag :email
  = text_field_tag :email
  = label_tag :password
  = password_field_tag :password
  = submit_tag "Login"

admin-rails/app/views/session/new.html.haml
.sign_form
  %h1 Log in
  = render 'form'

admin-rails/app/views/speakers/_form.html.haml
%p
  = f.label :name, "Name: "
  = f.text_field :name

%p
  = f.label :blurb, "Blurb: "
  = f.text_field :blurb

%p
  = f.label :image_url, "Local Avatar Upload : "

  -if @speaker.image?
    = image_tag(speaker.image) if speaker.image?
  = f.file_field :image_url

  / = f.label :image_url, "Remote Avatar Upload : "
  / = f.text_field :remote_image_url

%p
  should probs put in connection to user account password here?

%p
  = f.submit

admin-rails/app/views/speakers/edit.html.haml
%div.content
  %h1 Speakers#edit

  %div.speaker_form
    = form_for @speaker, html: { multipart: true } do |f|
      = render :partial => "form", :locals => {:f => f, :speaker => @speaker}


  - if !@errors.nil?
    %ul.Signup_Errors
    - for message_error in @errors
      %li
        * #{message_error}

admin-rails/app/views/speakers/index.html.haml
%div.content.speakers
  %h1 All Speakers

  - @speakers.each do |speaker|
    %a{:href=>"/speakers/#{speaker.id}"}
      %article.speaker
        %p.speaker_avatar
          -if speaker[:image].nil?
            %image{:src=>"http://placehold.it/200x200"}
          -else
            = image_tag speaker.image

        %h1= speaker.name
        %p= speaker.blurb
        %p.speaker_operation
          =link_to 'Edit', "/speakers/#{speaker.id}/edit"
          =link_to 'Delete', "/speakers/#{speaker.id}", :method => "delete"

admin-rails/app/views/speakers/new.html.haml
%div.content
  %h1 Speakers#new

  .speaker_form
    = form_for @speaker do |f|
      = render :partial => "form", :locals => {:f => f}

  - if !@errors.nil?
    %ul.Signup_Errors
    - for message_error in @errors
      %li
        * #{message_error}

admin-rails/app/views/speakers/show.html.haml
%div.content.row
  %h1 Speakers#show
  %div.row
    %div.speaker-info.medium-9.column
      %p= @speaker.name
      %p= @speaker.blurb
      =link_to 'Edit', edit_speaker_path
    %div.speaker_avatar.medium-3.column
      = image_tag @speaker.image
      /%image{:src=>"http://placehold.it/200x200"}

  %div.row
    %h1 My Talk
    %section.speaker_talks.medium-9.column
      - @talks.each do |talk|
        %a{:href => "/talks/#{talk.id}/edit"}
          %article.talk
            %h2
              =talk.title
            %h4
              =talk.blurb

      %a{:href => "/talks/speaker/1"}
        %article
          %button#add_talk
            +


      /%button#add_talk Add Talk

  %div.row
    %section.talk_form

/ :javascript
/   $('#add_talk').on('click', function() {
/    / $('.talk_form').append(#{render 'new'});
/   });

admin-rails/app/views/talks/_form.html.haml
%p
  = f.label :title, "Talk Title: "
  = f.text_field :title
%p
  = f.label :blurb, "Talk Blurb: "
  = f.text_field :blurb

%p
  = f.label :description, "Talk Description: "
  = f.text_area :description

%p
  = f.label :speaker_id, "Speaker"
  - binding.pry
  = f.select("speaker_id", Speaker.all.collect {|sp| [sp.name.capitalize, sp.id]}, :selected=>@talk.speaker_id)

%p
  = f.label :date, "Talk Date: "
  = f.date_field :date, :value => "2015-05-29", :disabled =>"true"

%p#duration
  = f.label :duration, "Talk Duration: "
  %span
    %em 15
    mins
  /= f.range_field :time, :step =>20, :value => 20, :min =>20, :max=>60
= f.hidden_field :duration, :value =>15
= f.hidden_field :limit, :value =>30

= f.submit

admin-rails/app/views/talks/edit.haml
%div.content
  %h1 Talks#edit_talk
  .talk_form
  = form_for @talk do |f|
    = render :partial => "form", :locals => {:f => f, :talk => @talk}


  :javascript
    $('#duration input[type="range"').on('change', function() {
      $parent = $(this).parent();
      $parent.find('em').html($(this).val());
      console.log($(this).val())
    });

admin-rails/app/views/talks/index.html.haml
%div.small-9.columns
  - (9..16).each do |row|
    %ul.small-block-grid-4
      - ["00","15","30","45"].each do |col|
        %div.single-talk.larger-talk-box
          %span.cell-time
            %li.inline-block= "#{row}:#{col}"
          %div.cell-content.dropTarget

%div.small-3.columns#talk-list
  %h2 All Talks
  - @talks.each do |talk|
    %div.single-talk
      %div
        %h1
          Title:
          = talk.title
        %p
          Blurb:
          = talk.blurb
        %p
          Speaker:
          = talk.speaker.name
        %p
          =link_to 'Edit', "/talks/#{talk.id}/edit"
          / by
          / = talk.speaker.name
          / %a{:href => "#{talk.id}/profile"} Show
          / %a{:href => "#{talk.id}/edit"} Edit
          %div.talk-box-close x
%div.result
:javascript
  $(function() {

  });
  $('#talk-list').sortable();
  talk_draggable();
  $('.dropTarget').on('load',function() {
    console.log('hello');
  });
  // $.get( "/talks/api/json", function( data ) {

  //   $.each(data, function(index, key) {
  //     debugger;
  //     $currentData = $(this);
  //     $currentData = $currentData[0].start_time;
  //     $match = false;
  //     $matchElement = "";
  //     $title = "";
  //     $allDropTarget = $('.single-talk');

  //     $.each($allDropTarget, function() {
  //       $timeData = $(this).find('span li').html();
  //       $droppableElem = $(this).find('.dropTarget');

  //       if($timeData === $currentData) {
  //         $match = true;
  //         $matchElement = $(this);

  //       }
  //     });

  //     if($match) {
  //       $title = $('h1').html('Title: '+ key.title);
  //       //debugger;
  //       $matchElement.find('.dropTarget').append($title[0]).removeClass('dropTarget');
  //     }
  //     console.log('dataEach');

  //   });
  //     //$('.currentTarget').parent().find('span li').html()
  // });

admin-rails/app/views/talks/my_talks.html.haml
%div.small-3.columns.content#talk-list
  %h2 All Talks
  - @talks.each do |talk|
    %div.single-talk.draggable
      %div
        %h1= talk.title
        %p= talk.blurb
        %p
          =link_to 'Edit', "/talks/#{talk.id}/edit"
          / by
          / = talk.speaker.name
          / %a{:href => "#{talk.id}/profile"} Show
          / %a{:href => "#{talk.id}/edit"} Edit
          %div.talk-box-close x

admin-rails/app/views/talks/new.html.haml
%div.content
  %h1 Add Talk
  .talk_form
    = form_for @talk do |f|
      = render :partial => "form", :locals => {:f => f}


  :javascript
    $('#duration input[type="range"').on('change', function() {
      $parent = $(this).parent();
      $parent.find('em').html($(this).val());
      console.log($(this).val())
    });

admin-rails/app/views/talks/new_by_speaker.html.haml
%div.content
  %h1 Add Talk
  .talk_form
    = form_for @talk do |f|
      = render :partial => "form", :locals => {:f => f}


  :javascript
    $('#duration input[type="range"').on('change', function() {
      $parent = $(this).parent();
      $parent.find('em').html($(this).val());
      console.log($(this).val())
    });

admin-rails/app/views/talks/show.html.haml
%div.content
  %h2 Talks#show

  %p= @talk.title
  %p= @talk.blurb

admin-rails/app/views/user_notifier/send_contact_email.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Hi there <%=@name%>, thanks for the message.</p>
    <p>We'll be in touch soon, just hold on tight!</p>
    <br>
    <p>Much love</p>
    <p>- The WDIConf crew</p>
    <img src="http://i.imgur.com/1xseKdL.png?1" alt="uxb logo">


  </body>
</html>

admin-rails/app/views/user_notifier/send_payment_email.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>Hi there <%=@first_name%>, here's your receipt you jerk!</p>


    <br>
    <p>Much love</p>
    <p>- The WDIConf crew</p>
    

    
    <img src="http://i.imgur.com/1xseKdL.png?1" alt="uxb logo">

  </body>
</html>

admin-rails/app/views/user_notifier/send_signup_email.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up, <%= @user.email %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
  </body>
</html>

admin-rails/app/views/user_notifier/send_signup_email.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    %h1
      Thanks for signing up, #{@user.email}!
    %p
      Thanks for joining and have a great day! Now sign in and do
      awesome things!

admin-rails/app/views/users/_form.html.haml
%p
  = label_tag :email, "Email: "
  = f.text_field :email

%p
  = label_tag :user_type, "Type: "
  = f.select("access_level_id", AccessLevel.all.collect {|a| [a.access_type.capitalize, a.id]}, :selected=>@user.access_level_id)

%p
  = label_tag :password, "Password: "
  = f.password_field :password

  = label_tag :password_conf, "Password Confirmation: "
  = f.password_field :password_confirmation

= f.hidden_field :login_type, :value =>@user.login_type||=1

admin-rails/app/views/users/_side_navbar.html.haml
%div.side-nav.medium-2.column
  %h2 Users
  %ul
    %li
      = link_to 'User Index', users_home_path
    %li
      = link_to 'Sign Up', user_signup_path
    %li
      = link_to 'Show all users', users_all_path

admin-rails/app/views/users/all.html.haml
%div.row
  = render "side_navbar"
  %div.content.medium-10.column

    %h2 All Users
    %table
      %thead
        %tr
          %th User Email
          %th User Type
          %th
          %th
      - @users.each do | user|
        %tr
          %td
            = user.email
          %td
            = @access_type[user.access_level_id-1].access_type
          %td
            %a{:href => "#{user.id}/profile"} Show
          %td
            %a{:href => "#{user.id}/edit"} Edit

admin-rails/app/views/users/edit.html.haml
%div.content
  %h1 Edit Profile

  %div.user_form
    = form_for :user, :action => user_update_path, :method =>:put  do |f|
      = render :partial => "form", :locals => {:f => f}
      = f.submit "Save User"

admin-rails/app/views/users/index.html.haml
%div.content
  %h1 Users index page
  %h2 All Users

  - @users.each do | user|
    %li #{user.email}

admin-rails/app/views/users/new.html.haml
%div.content
  %h1 Users#new

  %div.user_form
    = form_for :user, :action => user_signup_path  do |f|
      = render :partial => "form", :locals => {:f => f}
      = f.submit "Sign Up"

  - if !@errors.nil?
    %ul.Signup_Errors
    - for message_error in @errors
      %li
        * #{message_error}

admin-rails/app/views/users/profile.html.haml
%div.content
  %h1 Users#profile

  %p
    Email:
    = @user.email
  %p
    Access Type:
    = @user.access_level.access_type